### ISSUE TITLE
Emoji characters in dashboard title causes an error

### ISSUE THREAD

**Issue by ilativity** [ysde/grafana-backup-tool#149]
Hi,

I have added some emoji characters to the dashboards titles and this is causes an error in backup process
ex. for a title: 👩 Pola users 
Grafana version 8.1.3

**stack trace:**

Traceback (most recent call last):
  File "D:\Projects\grafana-backup-tool-master 2021-09-26\grafana-backup-tool-master\grafana_backup\commons.py", line 14, in log_response
    print("[DEBUG] resp body: {0}".format(resp.json()))
  File "C:\Users\VitVit\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f3e9' in position 5704: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VitVit\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\VitVit\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Projects\grafana-backup-tool-master 2021-09-26\grafana-backup-tool-master\grafana_backup\cli.py", line 60, in <module>
    main()
  File "D:\Projects\grafana-backup-tool-master 2021-09-26\grafana-backup-tool-master\grafana_backup\cli.py", line 46, in main
    save(args, settings)
  File "D:\Projects\grafana-backup-tool-master 2021-09-26\grafana-backup-tool-master\grafana_backup\save.py", line 51, in main
    backup_functions[backup_function](args, settings)
  File "D:\Projects\grafana-backup-tool-master 2021-09-26\grafana-backup-tool-master\grafana_backup\save_dashboards.py", line 26, in main
    save_dashboards_above_Ver6_2(folder_path, log_file, grafana_url, http_get_headers, verify_ssl, client_cert, debug, pretty_print, uid_support)
  File "D:\Projects\grafana-backup-tool-master 2021-09-26\grafana-backup-tool-master\grafana_backup\save_dashboards.py", line 80, in save_dashboards_above_Ver6_2
    dashboards = get_all_dashboards_in_grafana(current_page, limit, grafana_url, http_get_headers, verify_ssl, client_cert, debug)
  File "D:\Projects\grafana-backup-tool-master 2021-09-26\grafana-backup-tool-master\grafana_backup\save_dashboards.py", line 32, in get_all_dashboards_in_grafana
    (status, content) = search_dashboard(page,
  File "D:\Projects\grafana-backup-tool-master 2021-09-26\grafana-backup-tool-master\grafana_backup\dashboardApi.py", line 77, in search_dashboard
    return send_grafana_get(url, http_get_headers, verify_ssl, client_cert, debug)
  File "D:\Projects\grafana-backup-tool-master 2021-09-26\grafana-backup-tool-master\grafana_backup\dashboardApi.py", line 283, in send_grafana_get
    log_response(r)
  File "D:\Projects\grafana-backup-tool-master 2021-09-26\grafana-backup-tool-master\grafana_backup\commons.py", line 16, in log_response
    print("[DEBUG] resp body: {0}".format(resp.text))
  File "C:\Users\VitVit\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 5239-5241: character maps to <undefined>

**Comment by acjohnson** [comment]
This might be solved by https://github.com/ysde/grafana-backup-tool/pull/163 if you could test I would appreciate it @ilativity

**Comment by acjohnson** [comment]
This should be solved in latest `master` branch
