### ISSUE TITLE
ImportError: No module named ordered_dict

### ISSUE THREAD

**Issue by lduriez** [ysde/grafana-backup-tool#15]
Hello,

I try to launch the backup_grafana.sh but I have the following error : 
```bash
./backup_grafana.sh 
2019-01-28_14:10:33
Traceback (most recent call last):
  File "/opt/grafana-backup-tool/saveDashboards.py", line 2, in <module>
    from dashboardApi import *
  File "/opt/grafana-backup-tool/dashboardApi.py", line 1, in <module>
    import requests, json, re
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 80, in <module>
    from . import utils
  File "/usr/lib/python2.7/dist-packages/requests/utils.py", line 25, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/usr/lib/python2.7/dist-packages/requests/compat.py", line 94, in <module>
    from urllib3.packages.ordered_dict import OrderedDict
ImportError: No module named ordered_dict
Traceback (most recent call last):
  File "/opt/grafana-backup-tool/saveDatasources.py", line 2, in <module>
    from dashboardApi import *
  File "/opt/grafana-backup-tool/dashboardApi.py", line 1, in <module>
    import requests, json, re
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 80, in <module>
    from . import utils
  File "/usr/lib/python2.7/dist-packages/requests/utils.py", line 25, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/usr/lib/python2.7/dist-packages/requests/compat.py", line 94, in <module>
    from urllib3.packages.ordered_dict import OrderedDict
ImportError: No module named ordered_dict
Traceback (most recent call last):
  File "/opt/grafana-backup-tool/saveFolders.py", line 2, in <module>
    from dashboardApi import *
  File "/opt/grafana-backup-tool/dashboardApi.py", line 1, in <module>
    import requests, json, re
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 80, in <module>
    from . import utils
  File "/usr/lib/python2.7/dist-packages/requests/utils.py", line 25, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/usr/lib/python2.7/dist-packages/requests/compat.py", line 94, in <module>
    from urllib3.packages.ordered_dict import OrderedDict
ImportError: No module named ordered_dict
tar: Removing leading `/' from member names
/tmp/dashboards/2019-01-28_14:10:33/
tar: Removing leading `/' from member names
/tmp/datasources/2019-01-28_14:10:33/
tar: Removing leading `/' from member names
/tmp/folders/2019-01-28_14:10:33/
```

Did someone had the same issue and/or know what should I do ?

**Comment by ysde** [comment]
Hi lduriez 

I think this might relate to urlib3 module's version you have.

Can you check on this to see if it works or not?
https://github.com/jofpin/trape/issues/77

FYI

**Comment by lduriez** [comment]
I used python3 instead of python2 and all was fine. Thanks
