### ISSUE TITLE
does not work with latest grafana version

### ISSUE THREAD

**Issue by MarcusCaepio** [ysde/grafana-backup-tool#16]
Hi all,
wanted to try this but doesn't get it working.
Grafana URL is using https, grafana version is 6.0.2, Api got admin rights, when executing the backup script, I got:

2019-03-20_15:55:29
search dashboard in grafana:
Traceback (most recent call last):
  File "/root/grafana-backup-tool/saveDashboards.py", line 45, in <module>
    dashboards = get_all_dashboards_in_grafana()
  File "/root/grafana-backup-tool/saveDashboards.py", line 15, in get_all_dashboards_in_grafana
    status_and_content_of_all_dashboards = search_dashboard()
  File "/root/grafana-backup-tool/dashboardApi.py", line 7, in search_dashboard
    r = send_grafana_get(grafana_url + '/api/search/?type=dash-db&limit=' + search_api_limit)
TypeError: cannot concatenate 'str' and 'int' objects

Thanks in advanced.
Cheers,
Marcus

**Comment by MarcusCaepio** [comment]
Looks better, but I have to skip SSL verification:
```
2019-03-21_13:09:16
search dashboard in grafana:
Traceback (most recent call last):
  File "/root/grafana-backup-tool/saveDashboards.py", line 45, in <module>
    dashboards = get_all_dashboards_in_grafana()
  File "/root/grafana-backup-tool/saveDashboards.py", line 15, in get_all_dashboards_in_grafana
    status_and_content_of_all_dashboards = search_dashboard()
  File "/root/grafana-backup-tool/dashboardApi.py", line 7, in search_dashboard
    r = send_grafana_get(grafana_url + '/api/search/?type=dash-db&limit={0}'.format(search_api_limit))
  File "/root/grafana-backup-tool/dashboardApi.py", line 65, in send_grafana_get
    r = requests.get(url, headers=http_get_headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 480, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 588, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

**Comment by ysde** [comment]
I see, I only tested this with "http".
I pushed a latest [commit](3a46f3f24ee586fed66dc23d7ef6c098fc76ac01) for this. Can you help verify it?

Thank you

**Comment by ArcolaJasper** [comment]
Could you make skipping the verification a command line option? We have real certs for our grafana install and the warning is annoying.

I guess I could send a PR?

**Comment by borjasueiro** [comment]
Can you do the same  in  "send_grafana_post" method?
_r = requests.post(url, headers=http_post_headers, data=json_payload)
change by
_r = requests.post(url, headers=http_post_headers, data=json_payload, verify=verifySSL)_

**Comment by MarcusCaepio** [comment]
SSL is fixed, but I got another problem:
Traceback (most recent call last):
  File "/root/grafana-backup-tool/saveDashboards.py", line 47, in <module>
    get_indivisual_dashboard_setting_and_save(dashboards)
  File "/root/grafana-backup-tool/saveDashboards.py", line 38, in get_indivisual_dashboard_setting_and_save
    status_code_and_content = get_dashboard(board['uri'])
  File "/root/grafana-backup-tool/dashboardApi.py", line 11, in get_dashboard
    r = send_grafana_get(grafana_url + "/api/dashboards/{0}".format(board_uri))
  File "/root/grafana-backup-tool/dashboardApi.py", line 67, in send_grafana_get
    log_response(r)
  File "/root/grafana-backup-tool/commons.py", line 9, in log_response
    print("body: {0}".format(resp.content.decode('utf8')))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 15126: ordinal not in range(128)

**Comment by ArcolaJasper** [comment]
I had the same issue, using python3 worked.

**Comment by vitassecuriti** [comment]
I had this problem with Grafana 5.*
I runed script backup_garafana.sh and catched exception :
`query dashboard uri: db/allure-test-db, status: 200
Traceback (most recent call last):
  File "/home/talik/grafana-backup-tool/saveDashboards.py", line 47, in <module>
    get_indivisual_dashboard_setting_and_save(dashboards)
  File "/home/talik/grafana-backup-tool/saveDashboards.py", line 40, in get_indivisual_dashboard_setting_and_save
    save_dashboard_setting(board['title'], board['uid'], status_code_and_content[1])
  File "/home/talik/grafana-backup-tool/saveDashboards.py", line 32, in save_dashboard_setting
    f.write(dashboard_settings).encode('utf-8')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1222-1227: ordinal not in range(128)`

After i changed saveDashboards.py  i solved my problem
`save_dashboard_setting(board['title'].encode('utf-8'), board['uid'].encode('utf-8'), status_code_and_content[1].encode('utf-8'))
            file_path = folder_path + '/' + log_file
            with open(u"{0}".format(file_path) , 'w+') as f:
                f.write('{}\t{}'.format(board['uid'], board['title']).encode('utf-8'))`

**Comment by ysde** [comment]
> Could you make skipping the verification a command line option? We have real certs for our grafana install and the warning is annoying.
> 
> I guess I could send a PR?

Hi @ArcolaJasper
You can skip SSL verification by setting `verifySSL=False` in grafanaSettings.py
Is that ok to you ?

**Comment by ysde** [comment]
> Can you do the same in "send_grafana_post" method?
> _r = requests.post(url, headers=http_post_headers, data=json_payload)
> change by
> _r = requests.post(url, headers=http_post_headers, data=json_payload, verify=verifySSL)_

I've pushed latest commit adding this.
Thanks

**Comment by MarcusCaepio** [comment]
works now, thanks a lot!
