### ISSUE TITLE
UnicodeEncodeError in log_response

### ISSUE THREAD

**Issue by ankujuniyal** [ysde/grafana-backup-tool#160]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/grafana_backup/commons.py", line 14, in log_response
    print("[DEBUG] resp body: {0}".format(resp.json()))
UnicodeEncodeError: 'ascii' codec can't encode character '\xb5' in position 30086: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/grafana-backup", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/grafana_backup/cli.py", line 52, in main
    save(args, settings)
  File "/usr/local/lib/python3.6/site-packages/grafana_backup/save.py", line 51, in main
    backup_functions[backup_function](args, settings)
  File "/usr/local/lib/python3.6/site-packages/grafana_backup/save_dashboards.py", line 26, in main
    save_dashboards_above_Ver6_2(folder_path, log_file, grafana_url, http_get_headers, verify_ssl, client_cert, debug, pretty_print, uid_support)
  File "/usr/local/lib/python3.6/site-packages/grafana_backup/save_dashboards.py", line 86, in save_dashboards_above_Ver6_2
    get_individual_dashboard_setting_and_save(dashboards, folder_path, log_file, grafana_url, http_get_headers, verify_ssl, client_cert, debug, pretty_print, uid_support)
  File "/usr/local/lib/python3.6/site-packages/grafana_backup/save_dashboards.py", line 64, in get_individual_dashboard_setting_and_save
    (status, content) = get_dashboard(board_uri, grafana_url, http_get_headers, verify_ssl, client_cert, debug)
  File "/usr/local/lib/python3.6/site-packages/grafana_backup/dashboardApi.py", line 83, in get_dashboard
    (status_code, content) = send_grafana_get(url, http_get_headers, verify_ssl, client_cert, debug)
  File "/usr/local/lib/python3.6/site-packages/grafana_backup/dashboardApi.py", line 329, in send_grafana_get
    log_response(r)
  File "/usr/local/lib/python3.6/site-packages/grafana_backup/commons.py", line 16, in log_response
    print("[DEBUG] resp body: {0}".format(resp.text))
UnicodeEncodeError: 'ascii' codec can't encode character '\xb5' in position 27074: ordinal not in range(128)

**Comment by acjohnson** [comment]
@ankujuniyal Any idea where the `µ` character is coming from? Is it being used in your dashboard names?

I suspect we just need to standardize on `.encode('utf-8')` for our logging

**Comment by acjohnson** [comment]
@ankujuniyal would you be willing to test this patch to see if it makes any difference?
```shell
# git diff HEAD~1
diff --git a/grafana_backup/commons.py b/grafana_backup/commons.py
index bb747db..d6e24e4 100755
--- a/grafana_backup/commons.py
+++ b/grafana_backup/commons.py
@@ -13,7 +13,7 @@ def log_response(resp):
     try:
         print("[DEBUG] resp body: {0}".format(resp.json()))
     except ValueError:
-        print("[DEBUG] resp body: {0}".format(resp.text))
+        print("[DEBUG] resp body: {0}".format(resp.text.encode('utf-8')))
     return resp
```

**Comment by ankujuniyal** [comment]
@acjohnson  Did find µ character  in last logs Also try to replicate issue didn't face last error. Might be because i don't have last data on which i was working. sorry 
 
> @ankujuniyal Any idea where the `µ` character is coming from? Is it being used in your dashboard names?
> 
> I suspect we just need to standardize on `.encode('utf-8')` for our logging

**Comment by acjohnson** [comment]
@ankujuniyal I went ahead and filed https://github.com/ysde/grafana-backup-tool/pull/163 which may fix the issue. This should be a safe change either way so I'll see if we can get it merged.

**Comment by acjohnson** [comment]
@ankujuniyal without reproducing I'm having a hard time with this one. if you happen to run into this again it would help out greatly if you could try running `export GRAFANA_HEADERS=charset:utf-8` and re-run grafana-backup to see if this solves the error you are seeing. Thanks!

**Comment by acjohnson** [comment]
should be solved in latest `master` branch
