### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by AnthonyWC** [ysde/grafana-backup-tool#2]
```
ubuntu@ip-172-17-0-146:~/git/grafana-backup-tool$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10)

ubuntu@ip-172-17-0-146:~/git/grafana-backup-tool$ printenv | grep GRAFANA
GRAFANA_URL=http://ip-172-17-0-146:3000/grafana
GRAFANA_TOKEN=***********************************
```

I can curl to ip-172-17-0-146:3000/grafana and get back data.

```
ubuntu@ip-172-17-0-146:~/git/grafana-backup-tool$ python saveDatasources.py ../dashboard_backup/
search datasources in grafana:
Traceback (most recent call last):
  File "saveDatasources.py", line 27, in <module>
    datasources = get_all_datasources_and_save()
  File "saveDatasources.py", line 19, in get_all_datasources_and_save
    datasources = json.loads(content_of_datasources)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by ysde** [comment]
Sorry I cannot tell what the real problem is by this log.

My guess is the permission of the token is not enough. But the program didn't print the message.

I have done an upgraded version, it might help of debugging this problem. 

Thank you
