### ISSUE TITLE
saveDashboards.py cannot write to file

### ISSUE THREAD

**Issue by IngaFeick** [ysde/grafana-backup-tool#20]
Hi! I am using the current master of this project and while I can successfully export datasources and folders, the export of dashboards failes like so:

```
python saveDashboards.py /some-folder/
search dashboard in grafana:
There are 651 dashboards:
name: :: Bitbucket
name: :: Bot Traffic
...

########################################

query dashboard uri: db/bitbucket, status: 200
Traceback (most recent call last):
  File "saveDashboards.py", line 47, in <module>
    get_indivisual_dashboard_setting_and_save(dashboards)
  File "saveDashboards.py", line 40, in get_indivisual_dashboard_setting_and_save
    save_dashboard_setting(board['title'], board['uid'], status_code_and_content[1])
  File "saveDashboards.py", line 32, in save_dashboard_setting
    f.write(dashboard_settings.encode('utf-8'))
TypeError: write() argument must be str, not bytes

```

Grafana version is 5.4.2, os is Debian 9

**Comment by ysde** [comment]
Sorry there is a python2 and python3 string problem. 
The request library returns different result in different python version.
I'll fix this asap.

Thank you

**Comment by IngaFeick** [comment]
Thanks a lot @ysde

**Comment by ysde** [comment]
Hi @IngaFeick 

I've fixed it in latest commit. 

Can you help verify it? 
Thank you

**Comment by IngaFeick** [comment]
@ysde works now. Thanks a lot!
