### ISSUE TITLE
slim image is missing "packaging" module

### ISSUE THREAD

**Issue by tasiotas** [ysde/grafana-backup-tool#241]
Hi,

When I run slim version of docker image, I get this error

```
grafana-backup  | Traceback (most recent call last):
grafana-backup  |   File "/usr/bin/grafana-backup", line 5, in <module>
grafana-backup  |     from grafana_backup.cli import main
grafana-backup  |   File "/usr/lib/python3.11/site-packages/grafana_backup/cli.py", line 2, in <module>
grafana-backup  |     from grafana_backup.save import main as save
grafana-backup  |   File "/usr/lib/python3.11/site-packages/grafana_backup/save.py", line 1, in <module>
grafana-backup  |     from grafana_backup.api_checks import main as api_checks
grafana-backup  |   File "/usr/lib/python3.11/site-packages/grafana_backup/api_checks.py", line 2, in <module>
grafana-backup  |     from grafana_backup.dashboardApi import health_check, auth_check, uid_feature_check, paging_feature_check
grafana-backup  |   File "/usr/lib/python3.11/site-packages/grafana_backup/dashboardApi.py", line 6, in <module>
grafana-backup  |     from packaging import version
grafana-backup  | ModuleNotFoundError: No module named 'packaging'
```

On full image it works fine

Thank you

**Comment by acjohnson** [comment]
Resolved 5e121944b86912871bb9499de82431cd15813bad

Thanks @tasiotas !
