### ISSUE TITLE
TypeError in dashboardApi.py

### ISSUE THREAD

**Issue by ooaklee** [ysde/grafana-backup-tool#27]
Thanks for such a fantastic tool! One issue that came up for me and stopped me from performing a full dashboard restoration was that in the `get_folder_id_from_old_folder_url` function, `response[1]` was deemed a `dict` on some instances rather than a string which caused the `json.loads()` call to throw a `TypeError` error for me regularly. 

To fix it, I added the following if statement to replace line `45` (`folder_data = json.loads(response[1])`)

```
if isinstance(response[1],dict):
    folder_dict_to_str = json.dumps(response[1])
    # String to valid json
    folder_data = json.loads(folder_dict_to_str)   
else:
    folder_data = json.loads(response[1])
```

Are you able to implement this or something similar to the master branch, please?

**Comment by keyboardfann** [comment]
Hi @ooaklee,
    I also find the issue and also try to fix it. After testing your code, it works fine to me.
Here is my environment and testing:
Grafana version: 6.1.6
python:2.7.5
Original issue:
`➜  grafana-backup-tool git:(master) ✗ python createDashboard.py /root/1.json 
[debug] status: 200
[debug] body: {u'hasAcl': False, u'canAdmin': True, u'updated': u'2019-05-21T08:07:09Z', u'uid': u'8Luj-a1mk', u'title': u'DFT Game Ops', u'url': u'/dashboards/f/8Luj-a1mk/dft-game-ops', u'created': u'2019-05-21T08:07:09Z', u'canSave': True, u'canEdit': True, u'version': 1, u'createdBy': u'Anonymous', u'updatedBy': u'Anonymous', u'id': 7}
query folder:8Luj-a1mk, status:200
Traceback (most recent call last):
  File "createDashboard.py", line 18, in <module>
    'folderId': get_folder_id_from_old_folder_url(content['meta']['folderUrl']),
  File "/root/grafana-backup-tool/dashboardApi.py", line 45, in get_folder_id_from_old_folder_url
    folder_data = json.loads(response[1])
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
`

New fix code:
`➜  grafana-backup-tool git:(master) ✗ python createDashboard.py /root/1.json
[debug] status: 200
[debug] body: {u'hasAcl': False, u'canAdmin': True, u'updated': u'2019-05-21T08:07:09Z', u'uid': u'8Luj-a1mk', u'title': u'DFT Game Ops', u'url': u'/dashboards/f/8Luj-a1mk/dft-game-ops', u'created': u'2019-05-21T08:07:09Z', u'canSave': True, u'canEdit': True, u'version': 1, u'createdBy': u'Anonymous', u'updatedBy': u'Anonymous', u'id': 7}
query folder:8Luj-a1mk, status:200
[debug] status: 200
[debug] body: {u'status': u'success', u'uid': u'7lpNz4bmz', u'url': u'/d/7lpNz4bmz/registrationapi', u'slug': u'registrationapi', u'version': 3, u'id': 413}
create response status: 200, msg: {u'status': u'success', u'uid': u'7lpNz4bmz', u'url': u'/d/7lpNz4bmz/registrationapi', u'slug': u'registrationapi', u'version': 3, u'id': 413`


Hi @ysde,
    I have tested the fixed code.Could you help to merge the pull request #28.

**Comment by ysde** [comment]
I've merged the pull request.

May I know in what circumstances the response will become a `dict`?

Thank you all.

**Comment by keyboardfann** [comment]
Hi @ysde,
    It seems the Content is dict.

Test dashboard, export from saveDashboards.py
```
➜  grafana-backup-tool git:(master) ✗ cat /root/000000026.dashboard |python -m json.tool
{
    "dashboard": {
        "annotations": {
            "list": [
                {
                    "builtIn": 1,
                    "datasource": "-- Grafana --",
                    "enable": true,
                    "hide": true,
                    "iconColor": "rgba(0, 211, 255, 1)",
                    "name": "Annotations & Alerts",
                    "type": "dashboard"
                }
            ]
        },
        "editable": true,
        "gnetId": null,
        "graphTooltip": 0,
        "id": 26,
        "links": [],
        "panels": [
            {
                "content": "<div class=\"text-center dashboard-header\">\n  <span>Home Dashboard</span>\n</div>",
                "editable": true,
                "gridPos": {
                    "h": 3,
                    "w": 24,
                    "x": 0,
                    "y": 0
                },
                "id": 1,
                "links": [],
                "mode": "html",
                "style": {},
                "title": "",
                "transparent": true,
                "type": "text"
            },
            {
                "gridPos": {
                    "h": 13,
                    "w": 14,
                    "x": 0,
                    "y": 3
                },
                "headings": true,
                "id": 3,
                "limit": 10,
                "links": [],
                "query": "",
                "recent": true,
                "search": false,
                "starred": true,
                "tags": [],
                "title": "",
                "transparent": false,
                "type": "dashlist"
            },
            {
                "editable": true,
                "error": false,
                "gridPos": {
                    "h": 13,
                    "w": 10,
                    "x": 14,
                    "y": 3
                },
                "id": 4,
                "isNew": true,
                "links": [],
                "title": "",
                "transparent": false,
                "type": "pluginlist"
            }
        ],
        "schemaVersion": 16,
        "style": "dark",
        "tags": [],
        "templating": {
            "list": []
        },
        "time": {
            "from": "now-6h",
            "to": "now"
        },
        "timepicker": {
            "enable": false,
            "refresh_intervals": [
                "5s",
                "10s",
                "30s",
                "1m",
                "5m",
                "15m",
                "30m",
                "1h",
                "2h",
                "1d"
            ],
            "time_options": [
                "5m",
                "15m",
                "1h",
                "6h",
                "12h",
                "24h",
                "2d",
                "7d",
                "30d"
            ],
            "type": "timepicker"
        },
        "timezone": "browser",
        "title": "Home",
        "uid": "000000026",
        "version": 2
    },
    "meta": {
        "canAdmin": true,
        "canEdit": true,
        "canSave": true,
        "canStar": true,
        "created": "2016-10-05T15:04:27+08:00",
        "createdBy": "admin",
        "expires": "0001-01-01T00:00:00Z",
        "folderId": 604,
        "folderTitle": "1. Main",
        "folderUrl": "/dashboards/f/hFF71xbmk/1-main",
        "hasAcl": false,
        "isFolder": false,
        "provisioned": false,
        "slug": "home",
        "type": "db",
        "updated": "2018-10-23T14:13:50+08:00",
        "updatedBy": "admin",
        "url": "/d/000000026/home",
        "version": 2
    }
}

```

Modify createDashboard.py to print the dict
```
import json, sys, re, argparse
from dashboardApi import *

parser = argparse.ArgumentParser()
parser.add_argument('path',  help='file path saved of datasources\' setting')
args = parser.parse_args()

file_path = args.path

with open(file_path, 'r') as f:
    data = f.read()

content = json.loads(data)
content['dashboard']['id'] = None

print(type(content))
print(content)
payload = {
    'dashboard': content['dashboard'],
    'folderId': get_folder_id_from_old_folder_url(content['meta']['folderUrl']),
    'overwrite': True
}

result = create_dashboard(json.dumps(payload))

print("create response status: {0}, msg: {1}".format(result[0], result[1]))

```

Result
```
python createDashboard.py /root/000000026.dashboard
<type 'dict'>
{u'meta': {u'provisioned': False, u'hasAcl': False, u'canAdmin': True, u'updated': u'2018-10-23T14:13:50+08:00', u'createdBy': u'admin', u'canEdit': True, u'created': u'2016-10-05T15:04:27+08:00', u'url': u'/d/000000026/home', u'canStar': True, u'expires': u'0001-01-01T00:00:00Z', u'isFolder': False, u'canSave': True, u'folderTitle': u'1. Main', u'version': 2, u'folderUrl': u'/dashboards/f/hFF71xbmk/1-main', u'updatedBy': u'admin', u'folderId': 604, u'type': u'db', u'slug': u'home'}, u'dashboard': {u'style': u'dark', u'templating': {u'list': []}, u'links': [], u'title': u'Home', u'graphTooltip': 0, u'tags': [], u'editable': True, u'id': None, u'gnetId': None, u'timepicker': {u'time_options': [u'5m', u'15m', u'1h', u'6h', u'12h', u'24h', u'2d', u'7d', u'30d'], u'enable': False, u'type': u'timepicker', u'refresh_intervals': [u'5s', u'10s', u'30s', u'1m', u'5m', u'15m', u'30m', u'1h', u'2h', u'1d']}, u'version': 2, u'time': {u'to': u'now', u'from': u'now-6h'}, u'timezone': u'browser', u'schemaVersion': 16, u'panels': [{u'style': {}, u'links': [], u'title': u'', u'editable': True, u'id': 1, u'content': u'<div class="text-center dashboard-header">\n  <span>Home Dashboard</span>\n</div>', u'mode': u'html', u'gridPos': {u'y': 0, u'h': 3, u'w': 24, u'x': 0}, u'type': u'text', u'transparent': True}, {u'search': False, u'links': [], u'title': u'', u'tags': [], u'id': 3, u'limit': 10, u'headings': True, u'gridPos': {u'y': 3, u'h': 13, u'w': 14, u'x': 0}, u'query': u'', u'starred': True, u'type': u'dashlist', u'transparent': False, u'recent': True}, {u'links': [], u'title': u'', u'isNew': True, u'editable': True, u'id': 4, u'error': False, u'gridPos': {u'y': 3, u'h': 13, u'w': 10, u'x': 14}, u'type': u'pluginlist', u'transparent': False}], u'annotations': {u'list': [{u'enable': True, u'hide': True, u'name': u'Annotations & Alerts', u'builtIn': 1, u'datasource': u'-- Grafana --', u'type': u'dashboard', u'iconColor': u'rgba(0, 211, 255, 1)'}]}, u'uid': u'000000026'}}
[debug] status: 200
[debug] body: {u'hasAcl': False, u'canAdmin': True, u'updated': u'2019-05-21T08:07:08Z', u'uid': u'hFF71xbmk', u'title': u'1. Main', u'url': u'/dashboards/f/hFF71xbmk/1-main', u'created': u'2019-05-21T08:07:08Z', u'canSave': True, u'canEdit': True, u'version': 1, u'createdBy': u'Anonymous', u'updatedBy': u'Anonymous', u'id': 1}
query folder:hFF71xbmk, status:200
Traceback (most recent call last):
  File "createDashboard.py", line 20, in <module>
    'folderId': get_folder_id_from_old_folder_url(content['meta']['folderUrl']),
  File "/root/grafana-backup-tool/dashboardApi.py", line 45, in get_folder_id_from_old_folder_url
    folder_data = json.loads(response[1])
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
```
