### ISSUE TITLE
Does this work with ssl and oauth integration?

### ISSUE THREAD

**Issue by ttownsend78** [ysde/grafana-backup-tool#41]
I seem to be encountering errors, but I'm not sure if it is because my Grafana instance has SSO and SSL enabled. 

Error with the real URL:

```
[DEBUG] status: 404
Traceback (most recent call last):
  File "/root/grafana-backups/scripts/src/save_dashboards.py", line 67, in <module>
    (status, resp) = health_check()
  File "/root/grafana-backups/scripts/src/dashboardApi.py", line 8, in health_check
    return send_grafana_get(url)
  File "/root/grafana-backups/scripts/src/dashboardApi.py", line 73, in send_grafana_get
    log_response(r)
  File "/root/grafana-backups/scripts/src/commons.py", line 16, in log_response
    print("[DEBUG] body: {0}".format(resp.json()))
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 651, in json
    return json.loads(self.text or self.content, **kwargs)
  File "/usr/lib64/python2.7/dist-packages/simplejson/__init__.py", line 505, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python2.7/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

With localhost in grafanasettings.py

```
grafana health: http://localhost:3000/api/health
[DEBUG] status: 200
Traceback (most recent call last):
  File "/root/grafana-backups/scripts/src/save_dashboards.py", line 67, in <module>
    (status, resp) = health_check()
  File "/root/grafana-backups/scripts/src/dashboardApi.py", line 8, in health_check
    return send_grafana_get(url)
  File "/root/grafana-backups/scripts/src/dashboardApi.py", line 73, in send_grafana_get
    log_response(r)
  File "/root/grafana-backups/scripts/src/commons.py", line 16, in log_response
    print("[DEBUG] body: {0}".format(resp.json()))
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 651, in json
    return json.loads(self.text or self.content, **kwargs)
  File "/usr/lib64/python2.7/dist-packages/simplejson/__init__.py", line 505, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python2.7/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by ysde** [comment]
Sorry I didn't use ssl and oauth integration before.

I'll try them when I'm available.

Thanks

**Comment by ysde** [comment]
Hi @ttownsend78 

Do you have more detailed explanation of your grafana  instance's settings ?

Thank you

**Comment by dfluff** [comment]
For the record I use this with a Grafana install that both has TLS (...SSL) enabled, and uses OAuth and it works fine.  Could the issue be that you've got http rather than https in your config file?  The second example shows ``grafana health: http://localhost:3000/api/health`` which should surely be ``https://localhost:3000/api/health``

**Comment by fsperling** [comment]
Yeah, it works with SSL. And OAuth doesn't matter because the REST API uses the Authentication HTTP header.
