### ISSUE TITLE
Unable to backup Grafana 7.0.0 dashboards.

### ISSUE THREAD

**Issue by amadeuszkryze** [ysde/grafana-backup-tool#60]
Hi, recently I've upgraded Grafana server to version 7.0, and backup tool cannot backup dashboards from it.

Here is traceback from the container:
```
Backing up grafana
/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'beta-grafana.xyz.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
grafana health: https://beta-grafana.xyz.com:443//api/health
[DEBUG] status: 200
Traceback (most recent call last):
  File "./src/save_dashboards.py", line 75, in <module>
    (status, resp) = health_check()
  File "/opt/grafana-backup-tool/src/dashboardApi.py", line 29, in health_check
    return send_grafana_get(url)
  File "/opt/grafana-backup-tool/src/dashboardApi.py", line 106, in send_grafana_get
    log_response(r)
  File "/opt/grafana-backup-tool/src/commons.py", line 18, in log_response
    print("[DEBUG] body: {0}".format(resp.json()))
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Mikey1993** [comment]
Some questions:
1) Are you sure you are using `VERIFY_SSL = False` in the config file?
2) What is your `requests` package version? The latest is `2.23.0`, check [here](https://pypi.org/project/requests/#history)
3) Have you tried the suggested methods [here](https://stackoverflow.com/questions/27981545/suppress-insecurerequestwarning-unverified-https-request-is-being-made-in-pytho) ?

**Comment by amadeuszkryze** [comment]
I was running it in docker. But I'll try this 'VERIFY_SSL = False'. However I'm using valid SSL cert from let's encrypt.

**Comment by Mikey1993** [comment]
I don't have experience using the docker version, but it should be identical to running it not in a container..

**Comment by amadeuszkryze** [comment]
I mean its container from the creator of grafana-backup-tool. And it's not working, even after setting VERIFY_SSL to False. However, its not a problem with connection but with json decode inside this tool.

**Comment by Mikey1993** [comment]
And running the backup procedure without a container works for you?

**Comment by rgarrigue** [comment]
I don't quite have the same issue. After cloning, editing the setting file with ssl yes, debug false, url & token I've this log

```
grafana health: https://grafana.company.cloud/api/health
search dashboard in grafana: https://grafana.company.cloud/api/search/?type=dash-db&limit=5000&page=1
There are 24 dashboards:
name: Alerts
name: Amazon CloudWatch Logs
name: Amazon EBS
name: Amazon EC2
name: Amazon RDS
name: Consul
name: Docker Engine
name: HAProxy
name: Instances
name: Logs
name: NGINX
name: Processes
name: RabbitMQ
name: URL monitoring blackbox
name: URL monitoring worldPing
name: Platform
name: worldPing Endpoint: Comparison
name: worldPing Endpoint: Summary
name: worldPing Endpoint: |--- DNS
name: worldPing Endpoint: |--- Ping
name: worldPing Endpoint: |--- Web
name: worldPing: Events
name: worldPing: Home
name: worldPing: Probes

########################################

query dashboard uri: https://grafana.company.cloud/api/dashboards/db/alerts
{'meta': {'type': 'db', 'canSave': False, 'canEdit': False, 'canAdmin': False, ...
...
[tons of json]
...
search dashboard in grafana: https://grafana.company.cloud/api/search/?type=dash-db&limit=5000&page=2
There are 0 dashboards:

########################################

search datasources in grafana:
query datasource failed, status: 403, msg: {'message': 'Permission denied'}

########################################

search folder in grafana:
There are 1 folders:
name: Unused

########################################

query folder:QgblaFyZz, status:200
folder are saved to _OUTPUT_/folders/2020-06-02T07-37-43/QgblaFyZz.folder

########################################

search alert channels in grafana: https://grafana.company.cloud/api/alert-notifications
query alert channels failed, status: 403, msg: {'message': 'Permission denied'}

########################################

_OUTPUT_/dashboards/2020-06-02T07-37-43/
_OUTPUT_/dashboards/2020-06-02T07-37-43/RFVQJKsWz.dashboard
_OUTPUT_/dashboards/2020-06-02T07-37-43/yK4Q1KyZz.dashboard
_OUTPUT_/dashboards/2020-06-02T07-37-43/zWzB6KyZk.dashboard
_OUTPUT_/dashboards/2020-06-02T07-37-43/blackbox.dashboard
_OUTPUT_/dashboards/2020-06-02T07-37-43/WojOgXTmk.dashboard
_OUTPUT_/dashboards/2020-06-02T07-37-43/M77ZFhsWz.dashboard
_OUTPUT_/dashboards/2020-06-02T07-37-43/Kd4w1FsWz.dashboard
_OUTPUT_/dashboards/2020-06-02T07-37-43/NuuHg5sZz.dashboard
_OUTPUT_/dashboards/2020-06-02T07-37-43/MP7gaHbZz.dashboard
_OUTPUT_/dashboards/2020-06-02T07-37-43/a3-4-FyZz.dashboard
_OUTPUT_/dashboards/2020-06-02T07-37-43/ZpVQ1KyZz.dashboard
_OUTPUT_/dashboards/2020-06-02T07-37-43/nvVQJFsWz.dashboard
_OUTPUT_/dashboards/2020-06-02T07-37-43/IdXMLhqZz.dashboard
_OUTPUT_/dashboards/2020-06-02T07-37-43/HdeaRHxWz.dashboard
_OUTPUT_/dashboards/2020-06-02T07-37-43/tmsOtSxZk.dashboard
_OUTPUT_/dashboards/2020-06-02T07-37-43/8pVw1FsZk.dashboard
_OUTPUT_/dashboards/2020-06-02T07-37-43/K58yzU9Zz.dashboard
_OUTPUT_/dashboards/2020-06-02T07-37-43/PDVQ1FsZk.dashboard
_OUTPUT_/dashboards/2020-06-02T07-37-43/nzsEA5gGz.dashboard
_OUTPUT_/dashboards/2020-06-02T07-37-43/g7j0xhjZk.dashboard
_OUTPUT_/dashboards/2020-06-02T07-37-43/Kn5xm-gZk.dashboard
_OUTPUT_/dashboards/2020-06-02T07-37-43/ccVQJKsZk.dashboard
_OUTPUT_/dashboards/2020-06-02T07-37-43/5lKoAHxZz.dashboard
_OUTPUT_/dashboards/2020-06-02T07-37-43/oZpynZ7mz.dashboard
_OUTPUT_/dashboards/2020-06-02T07-37-43/dashboards_202006020737.txt
_OUTPUT_/datasources/2020-06-02T07-37-43/
_OUTPUT_/folders/2020-06-02T07-37-43/
_OUTPUT_/folders/2020-06-02T07-37-43/QgblaFyZz.folder
_OUTPUT_/folders/2020-06-02T07-37-43/folders_202006020737.txt
_OUTPUT_/alert_channels/2020-06-02T07-37-43/
```

My versions : Grafana 7.0.1, and

```
~/work/grafana-backup-tool (master ✘)✹ ᐅ pip3 install -r requirements.txt
Requirement already satisfied: requests[security] in /home/remy/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (2.23.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/remy/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from requests[security]->-r requirements.txt (line 1)) (2020.4.5.1)
Requirement already satisfied: chardet<4,>=3.0.2 in /home/remy/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from requests[security]->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /home/remy/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from requests[security]->-r requirements.txt (line 1)) (2.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/remy/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from requests[security]->-r requirements.txt (line 1)) (1.25.9)
Requirement already satisfied: pyOpenSSL>=0.14; extra == "security" in /home/remy/.local/lib/python3.8/site-packages (from requests[security]->-r requirements.txt (line 1)) (19.1.0)
Requirement already satisfied: cryptography>=1.3.4; extra == "security" in /home/remy/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from requests[security]->-r requirements.txt (line 1)) (2.9.2)
Requirement already satisfied: six>=1.5.2 in /home/remy/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from pyOpenSSL>=0.14; extra == "security"->requests[security]->-r requirements.txt (line 1)) (1.15.0)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /home/remy/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from cryptography>=1.3.4; extra == "security"->requests[security]->-r requirements.txt (line 1)) (1.14.0)
Requirement already satisfied: pycparser in /home/remy/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=1.3.4; extra == "security"->requests[security]->-r requirements.txt (line 1)) (2.20)
```

**Comment by Mikey1993** [comment]
> 
> 
> For the feedback, I'm fine with 7.0.1 and
> 
> ```
> ~/work/grafana-backup-tool (master ✘)✹ ᐅ pip3 install -r requirements.txt
> Requirement already satisfied: requests[security] in /home/remy/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (2.23.0)
> Requirement already satisfied: certifi>=2017.4.17 in /home/remy/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from requests[security]->-r requirements.txt (line 1)) (2020.4.5.1)
> Requirement already satisfied: chardet<4,>=3.0.2 in /home/remy/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from requests[security]->-r requirements.txt (line 1)) (3.0.4)
> Requirement already satisfied: idna<3,>=2.5 in /home/remy/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from requests[security]->-r requirements.txt (line 1)) (2.9)
> Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/remy/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from requests[security]->-r requirements.txt (line 1)) (1.25.9)
> Requirement already satisfied: pyOpenSSL>=0.14; extra == "security" in /home/remy/.local/lib/python3.8/site-packages (from requests[security]->-r requirements.txt (line 1)) (19.1.0)
> Requirement already satisfied: cryptography>=1.3.4; extra == "security" in /home/remy/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from requests[security]->-r requirements.txt (line 1)) (2.9.2)
> Requirement already satisfied: six>=1.5.2 in /home/remy/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from pyOpenSSL>=0.14; extra == "security"->requests[security]->-r requirements.txt (line 1)) (1.15.0)
> Requirement already satisfied: cffi!=1.11.3,>=1.8 in /home/remy/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from cryptography>=1.3.4; extra == "security"->requests[security]->-r requirements.txt (line 1)) (1.14.0)
> Requirement already satisfied: pycparser in /home/remy/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=1.3.4; extra == "security"->requests[security]->-r requirements.txt (line 1)) (2.20)
> ```
> 
> I wish there wasn't the [tons of json] part, I tried to silence it w/o success.
> 
> I had a datasource + alerts channels issue KO due to permission denied, with an "admin" instead of "viewer" token its fine, could be documented.

@rgarrigue ,
What do you mean by "tons of json" part?
Can you elaborate?

Also, you are right that there is a need to use the `Admin` APIKey instead of a `viewer` key for the backup to succeed.
@ysde.
I have updated the README and pushed it into the documentation in my pull request.
can you merge?

**Comment by ysde** [comment]
@Mikey1993  thanks for the help
@rgarrigue Yeah, all the backups need Admin permission to proceed. 

Thank you
